import os

SEMANTIC_GRID_SIZE = int(os.environ.get('SEMANTIC_GRID_SIZE', '16'))

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

GEOMETRY_START_TOKEN = '<GEOMETRY_START>'
GEOMETRY_END_TOKEN = '<GEOMETRY_END>'
GEOM_CAMERA_TOKEN = '<GEOM_CAMERA>'
NUM_GEOM_PATCH_TOKENS = SEMANTIC_GRID_SIZE * SEMANTIC_GRID_SIZE
GEOM_PATCH_TOKENS = [f'<GEOM_PATCH_{i+1}>' for i in range(NUM_GEOM_PATCH_TOKENS)]

ALL_GEOMETRY_OUTPUT_TOKENS = (
    [GEOMETRY_START_TOKEN]
    + GEOM_PATCH_TOKENS
    + [GEOM_CAMERA_TOKEN, GEOMETRY_END_TOKEN]
)
NUM_ALL_GEOMETRY_OUTPUT_TOKENS = len(ALL_GEOMETRY_OUTPUT_TOKENS)

SEMANTIC_START_TOKEN = '<SEMANTIC_START>'
SEMANTIC_END_TOKEN = '<SEMANTIC_END>'
NUM_SEG_TOKENS = SEMANTIC_GRID_SIZE * SEMANTIC_GRID_SIZE
SEG_TOKENS = [f'<SEG_{i+1}>' for i in range(NUM_SEG_TOKENS)]

ALL_SEMANTIC_OUTPUT_TOKENS = (
    [SEMANTIC_START_TOKEN]
    + SEG_TOKENS
    + [SEMANTIC_END_TOKEN]
)
NUM_ALL_SEMANTIC_OUTPUT_TOKENS = len(ALL_SEMANTIC_OUTPUT_TOKENS)

POSE_TOKEN = '<POSE>'

VGGT_MULTI_LAYER_INDICES = [
    int(x) for x in os.environ.get('VGGT_MULTI_LAYER_INDICES', '4,11,17,23').split(',')
]
GEOMETRY_PATCH_DIM = 2048 * len(VGGT_MULTI_LAYER_INDICES)
GEOMETRY_CAM_DIM = 2048
NUM_GEOMETRY_PATCHES = 1024
